### ISSUE TITLE
The example does not work (no such file or directory)

### ISSUE THREAD

**Issue by Jan10** [Ariel-Rodriguez/react-amp-template#12]
Thanks for the project!

I get an error if I want to start the example:

```
npm start

> rampt-demo@1.0.0 start C:\xampp\htdocs\react-amp-template\examples\simple-server
> npm run build && npm run serve

> rampt-demo@1.0.0 build C:\xampp\htdocs\react-amp-template\examples\simple-server
> babel src -d dist -s && cd server && node render.js

src\App.jsx -> dist\App.js
src\Components\Body.jsx -> dist\Components\Body.js
src\Components\Head.jsx -> dist\Components\Head.js
src\Components\Heading.jsx -> dist\Components\Heading.js
src\Components\PostCard.jsx -> dist\Components\PostCard.js
src\Components\SocialShare.jsx -> dist\Components\SocialShare.js
src\globalStyles.js -> dist\globalStyles.js
C:\xampp\htdocs\react-amp-template\examples\simple-server\server\render.js:16
    throw Error(err)
    ^

Error: Error: ENOENT: no such file or directory, open 'C:\xampp\htdocs\react-amp-template\examples\simple-server\server\public\index.html'
    at fs.writeFile.err (C:\xampp\htdocs\react-amp-template\examples\simple-server\server\render.js:16:11)
    at fs.js:1279:7
    at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rampt-demo@1.0.0 build: `babel src -d dist -s && cd server && node render.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rampt-demo@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\B\AppData\Roaming\npm-cache\_logs\2018-05-08T11_31_03_772Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rampt-demo@1.0.0 start: `npm run build && npm run serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rampt-demo@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\B\AppData\Roaming\npm-cache\_logs\2018-05-08T11_31_03_809Z-debug.log

C:\xampp\htdocs\react-amp-template\examples\simple-server>
```

Npm log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\b\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.0.0
3 info using node@v8.11.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle rampt-demo@1.0.0~prestart: rampt-demo@1.0.0
6 info lifecycle rampt-demo@1.0.0~start: rampt-demo@1.0.0
7 verbose lifecycle rampt-demo@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle rampt-demo@1.0.0~start: PATH: C:\Users\b\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\xampp\htdocs\react-amp-template\examples\simple-server\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Ruby24-x64\bin;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;c:\app\oracle\product\11.2.0\client_1\bin;C:\WINDOWS\system32\oracle;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\Windows\SysWOW64;C:\Program Files (x86)\IBM\Client Access\Emulator;C:\Program Files (x86)\IBM\Client Access\Shared;C:\Program Files (x86)\IBM\Client Access\;C:\WINDOWS\idmu\common;C:\WINDOWS\System32\Windows System Resource Manager\bin;C:\Program Files (x86)\GnuWin32\bin;C:\WINDOWS\syswow64;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\7-Zip;C:\Program Files (x86)\Windows Live\Shared;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Program Files\Git\cmd;C:\Ruby21-x64\Bin\;C:\Ruby21\Bin\;C:\Program Files (x86)\Yarn\bin;C:\Program Files (x86)\Skype\Phone\;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\CenterTools\DriveLock\;C:\Program Files\nodejs\;C:\Users\b\AppData\Roaming\Composer\vendor\bin;C:\Users\b\AppData\Local\Yarn\bin;C:\Users\b\AppData\Local\Microsoft\WindowsApps;C:\Users\b\AppData\Roaming\npm
9 verbose lifecycle rampt-demo@1.0.0~start: CWD: C:\xampp\htdocs\react-amp-template\examples\simple-server
10 silly lifecycle rampt-demo@1.0.0~start: Args: [ '/d /s /c', 'npm run build && npm run serve' ]
11 silly lifecycle rampt-demo@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle rampt-demo@1.0.0~start: Failed to exec start script
13 verbose stack Error: rampt-demo@1.0.0 start: `npm run build && npm run serve`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\b\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:283:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\b\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid rampt-demo@1.0.0
15 verbose cwd C:\xampp\htdocs\react-amp-template\examples\simple-server
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\b\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.11.1
19 verbose npm  v6.0.0
20 error code ELIFECYCLE
21 error errno 1
22 error rampt-demo@1.0.0 start: `npm run build && npm run serve`
22 error Exit status 1
23 error Failed at the rampt-demo@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by Ariel-Rodriguez** [comment]
Hi @Jan10 

Thanks for reporting the issue.
I added a commit to fix it. Try to pull master and run `npm start` again.
It should work now.

**Comment by Jan10** [comment]
Works thanks!

When i run `npm build`, the `assets` folder is not in the `public` folder.

**Comment by Ariel-Rodriguez** [comment]
Great!

Yes you are right. I'll come back with a better codebase for production ready example.
Thanks again.
